services:
  postgres:
    image: postgres:16
    container_name: smart-support-postgres
    environment:
      POSTGRES_DB: supportdb
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: support_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: